### PR TITLE
Security Group Modifications

### PR DESCRIPTION
**Pull request by cab105**
Return the full security group blob instead of the associated Id.  This is required for the Terraform plugin to function properly.

### CODE REVIEW

**Comment by sebgoa** [comment]
@cab105 you need to rebase on master

**Comment by sebgoa** [comment]
and can you just send the pr directly to pyr/egoscale ?

**Comment by cab105** [comment]
This was pulled and resynced against pyr/egoscale's master branch before submitting this PR.  If the pyr/egoscale will be the official one going forward, then I'll submit the PR with them.

**Comment by sebgoa** [comment]
@cab105 yes we need to point to pyr/egoscale going forward.

cc/ @pyr

**Pull request closed without merging**
